### ISSUE TITLE
afterEach has already deleted deps when using Jasmine instead of Mocha

### ISSUE THREAD

**Issue by m1gu3l** [kensho/ng-describe#52]
```
beforeEach(function () {
  console.log(Object.keys(deps)); // -> [ 'dep1', 'dep2', 'step' ]
});

afterEach(function () {
  console.log(Object.keys(deps)); // -> [ 'step' ] :/
});
```

**Comment by KapuzenSohn** [comment]
Just stumble over the same issue

**Comment by mcamac** [comment]
Also reproduced - will take a look!

**Comment by mcamac** [comment]
So it seems that this is occurring due to `afterEach` `unshift`ing its callbacks onto its callback list - this matters because ngDescribe first runs the commands in your `tests` section and then adds a final `afterEach` which deletes keys in the dependencies object. Jasmine `unshift`s this, making the key deletion `afterEach` run first. Investigating a fix.

https://github.com/jasmine/jasmine/blob/750a9aac6d004a960fc752ce260600b68e06f711/lib/jasmine-core/jasmine.js#L2054

**Comment by bahmutov** [comment]
Mocha executes `afterEach` callback in *order written*, while Jasmine *reverses* the order.
```js
describe('after each callbacks', function () {
  // just a dummy unit test to figure out how afterEach callbacks run
  it('passes', function () {});

  afterEach(function one() {
    console.log('one');
  });

  afterEach(function one() {
    console.log('two');
  });

  afterEach(function one() {
    console.log('three');
  });
  /*
    result

    Jasmine:
      'three'
      'two'
      'one'

    Mocha:
      'one'
      'two'
      'three'
  */
});
```

Sad
